# Generated by Django 5.2.5 on 2025-08-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllowedIP',
        ),
    ]
